# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/imsanskar/My files/Projects/Newton Fractal"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/imsanskar/My files/Projects/Newton Fractal"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/imsanskar/My files/Projects/Newton Fractal/CMakeFiles" "/media/imsanskar/My files/Projects/Newton Fractal//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/imsanskar/My files/Projects/Newton Fractal/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NewtonFractal

# Build rule for target.
NewtonFractal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NewtonFractal
.PHONY : NewtonFractal

# fast build rule for target.
NewtonFractal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/build
.PHONY : NewtonFractal/fast

src/IndexBuffer.o: src/IndexBuffer.cpp.o

.PHONY : src/IndexBuffer.o

# target to build an object file
src/IndexBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/IndexBuffer.cpp.o
.PHONY : src/IndexBuffer.cpp.o

src/IndexBuffer.i: src/IndexBuffer.cpp.i

.PHONY : src/IndexBuffer.i

# target to preprocess a source file
src/IndexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/IndexBuffer.cpp.i
.PHONY : src/IndexBuffer.cpp.i

src/IndexBuffer.s: src/IndexBuffer.cpp.s

.PHONY : src/IndexBuffer.s

# target to generate assembly for a file
src/IndexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/IndexBuffer.cpp.s
.PHONY : src/IndexBuffer.cpp.s

src/Renderer.o: src/Renderer.cpp.o

.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Shaders.o: src/Shaders.cpp.o

.PHONY : src/Shaders.o

# target to build an object file
src/Shaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/Shaders.cpp.o
.PHONY : src/Shaders.cpp.o

src/Shaders.i: src/Shaders.cpp.i

.PHONY : src/Shaders.i

# target to preprocess a source file
src/Shaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/Shaders.cpp.i
.PHONY : src/Shaders.cpp.i

src/Shaders.s: src/Shaders.cpp.s

.PHONY : src/Shaders.s

# target to generate assembly for a file
src/Shaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/Shaders.cpp.s
.PHONY : src/Shaders.cpp.s

src/VertexArray.o: src/VertexArray.cpp.o

.PHONY : src/VertexArray.o

# target to build an object file
src/VertexArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/VertexArray.cpp.o
.PHONY : src/VertexArray.cpp.o

src/VertexArray.i: src/VertexArray.cpp.i

.PHONY : src/VertexArray.i

# target to preprocess a source file
src/VertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/VertexArray.cpp.i
.PHONY : src/VertexArray.cpp.i

src/VertexArray.s: src/VertexArray.cpp.s

.PHONY : src/VertexArray.s

# target to generate assembly for a file
src/VertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/VertexArray.cpp.s
.PHONY : src/VertexArray.cpp.s

src/VertexBuffer.o: src/VertexBuffer.cpp.o

.PHONY : src/VertexBuffer.o

# target to build an object file
src/VertexBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/VertexBuffer.cpp.o
.PHONY : src/VertexBuffer.cpp.o

src/VertexBuffer.i: src/VertexBuffer.cpp.i

.PHONY : src/VertexBuffer.i

# target to preprocess a source file
src/VertexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/VertexBuffer.cpp.i
.PHONY : src/VertexBuffer.cpp.i

src/VertexBuffer.s: src/VertexBuffer.cpp.s

.PHONY : src/VertexBuffer.s

# target to generate assembly for a file
src/VertexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/VertexBuffer.cpp.s
.PHONY : src/VertexBuffer.cpp.s

src/glad.o: src/glad.c.o

.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i

.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s

.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/math.o: src/math.cpp.o

.PHONY : src/math.o

# target to build an object file
src/math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/math.cpp.o
.PHONY : src/math.cpp.o

src/math.i: src/math.cpp.i

.PHONY : src/math.i

# target to preprocess a source file
src/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/math.cpp.i
.PHONY : src/math.cpp.i

src/math.s: src/math.cpp.s

.PHONY : src/math.s

# target to generate assembly for a file
src/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonFractal.dir/build.make CMakeFiles/NewtonFractal.dir/src/math.cpp.s
.PHONY : src/math.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NewtonFractal"
	@echo "... src/IndexBuffer.o"
	@echo "... src/IndexBuffer.i"
	@echo "... src/IndexBuffer.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Shaders.o"
	@echo "... src/Shaders.i"
	@echo "... src/Shaders.s"
	@echo "... src/VertexArray.o"
	@echo "... src/VertexArray.i"
	@echo "... src/VertexArray.s"
	@echo "... src/VertexBuffer.o"
	@echo "... src/VertexBuffer.i"
	@echo "... src/VertexBuffer.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/math.o"
	@echo "... src/math.i"
	@echo "... src/math.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

